### PR TITLE
CSS tweak

### PR DESCRIPTION
**Pull request by NickLewanowicz**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
- CSS tweak

### CODE REVIEW

**Comment by sglanzer** [comment]
Before/after screenshot by any chance?

**Comment by NickLewanowicz** [comment]
@sglanzer 
Before
after

**Comment by sglanzer** [comment]
Ok, how about the demo?  This is the current version 
image

I'm just concerned that we're fixing the case where the label is left-aligned, but may be introducing an issue for the top-aligned case

**Comment by NickLewanowicz** [comment]
Just checked @sglanzer and it does mess up the demo where the titles are above. So should this stay inside of NHP?

**Comment by sglanzer** [comment]
Really sorry for the super late response on this - if you need it immediately I would keep it inside of NHP/BPA and we can either close this and raise an issue or leave it open and explore other solutions to fixing both cases

**Comment by rox163** [comment]
I say lets close this and raise an issue. @NickLewanowicz can you raise the issue and make sure the styles stay in NHP? thanks

**Pull request closed without merging**
